apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: iris-serving-pipeline # executable ID, must be unique across your SAP AI Core instance, for example use `server-pipeline-yourname-1234`
  annotations:
    scenarios.ai.sap.com/name: "Iris DataSet Classifier Scenario" # Scenario name should be the use case
    scenarios.ai.sap.com/description: "SAP AI Core tutorial to classify the popular iris datase"

    executables.ai.sap.com/name: "irismodelserving" # Executable name should describe the workflow in the use case  
    executables.ai.sap.com/description: "Serving with popular iris dataset"

    artifacts.ai.sap.com/irismodel.kind: "model" # Suggest the kind of artifact to input.
  labels:
    scenarios.ai.sap.com/id: "iris-classifier-scenario"
    ai.sap.com/version: "4.0"
spec:
  inputs:
    artifacts:
      - name: irismodel # placeholder name, do not add `-` in value use only alphanumeric chars
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency   # condition when to scale
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter # computing power
    spec: |
      predictor:
        imagePullSecrets:
          - name: milton-credentials   # your docker registry secret
        minReplicas: 1
        maxReplicas: 5    # how much to scale
        containers:
        - name: kserve-container
          image: docker.io/miltonc/iris-ai-serving-image:04
          ports:
            - containerPort: 9001    # customizable port
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -e && echo "Starting" && gunicorn --chdir /app/src main:app -b 0.0.0.0:9001 # filename `main` flask variable `app`
          env:
            - name: STORAGE_URI # Required
              value: "{{inputs.artifacts.irismodel}}" # Required reference from artifact name, see above
